MILESTONE: POPUP WINDOWS
Amedzro-Elikplim/Portfolio pull request #10
Opened 2022-02-03 20:27 UTC by Amedzro-Elikplim

# POPUP MENU

- Add popup window to mobile view
- Add popup window to desktop view
- Create a project CSS file for a popup window
- Add javascript to toggle popup window in mobile and desktop view
- Format code to use DRY principle
- Add responsiveness to project images

2022-02-03 20:57 UTC, moise10r requested changes
### Hi **@Team,**

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻

- The popup is responsive, it fits mobile and desktop sizes properly.✔️ 
- You have a professional README file
-  You have a descriptive PR, keep rocking :rocket: 
 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏 💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-03 20:57 UTC, moise10r commented on index.html
> +      <div class="project-reverse project">
- [ ] Based on requirements all the content of popup modal is created dynamically with the information from the projects array (all the HTML of the section is created when the page loads). The JavaScript code should have an array of objects to store JavaScript objects containing the information for each project. Each object contains at least the following information about the project: name, description, featuring image, technologies, link to live version, and link to the project source code. Ie: eg:
````javascript
const projects = [{
    name: "Submarine game",
    description: "A Phaser3 plataformer game built as part of the Microverse JavaScript program.",
    image: "link_to_image.jpg",
    technologies: ["Phaser3", "JavaScript", "Jest"],
    link: "link_to_live_version.com",
}]
````
Please create an object and make the modal popup data populated with the data from the projects array. 😉



If you are struggling or don't know how to do so, here is an [example](https://github.com/olawale-o/portfolio-mobile-version/pull/15/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R95)

 - All those cards information should be stored into an array of objects then create a function to render through the array and create dynamically your HTML with the information from the object array, the works section must stay empty

2022-02-03 21:00 UTC, moise10r commented on project.css
> +
- [ ] Kindly add these icons to the `See live` and `See source` buttons of your popup window :arrow_down: 

Your design: 

![b1](https://user-images.githubusercontent.com/57562869/152427765-e579a11b-5cae-4cc4-8ccf-055e49bd3261.png)


Figma:

![b1](https://user-images.githubusercontent.com/57562869/152427815-b7e30228-947b-4af9-b468-4f574aec1b0a.png)

2022-02-05 00:12 UTC, micheaol approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hi @Amedzro-Elikplim , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 
- You set up linter files and no errors. 💯 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-05 00:37 UTC, merged